### PR TITLE
Add index, signin page. Support signout and flatten User into Current…

### PR DESCRIPTION
**Pull request by dreid**
Also support signout and flatten User into CurrentUser for usage in the rendering Context.

Some notable changes.

CurrentUser now includes access to the user object in addition to the session.

Signin/Signup have been combined into a single endpoint/form. There is a standalone signin page that is rendered on signin/up error.

A signout endpoint is added (it so far only deletes the session cookie.)

### CODE REVIEW

**Comment by richo** [comment]
Am I doing something super goofy?

I get:

```
error: procedural macros cannot be imported with `#[macro_use]`
   --> src/bin/server.rs:126:21
    |
17  | use failure::Error;
    | - help: instead, import the procedural macro like any other item: `use rocket_codegen_next::routes;`
...
126 |         .mount("/", routes![get_config, get_signin, signin, signout, index])
    |                     ^^^^^^

```

When I try to run it, although it's green on travis and presumably worked for you. I just did a `cargo update` so I don't think I have out of date dependencies.

**Comment by dreid** [comment]
Maybe you have a newer nightly?

**Comment by richo** [comment]
No idea. I’ll have a look when I get home. Could you gist your cargo.lock?

**Comment by dreid** [comment]
https://gist.github.com/dreid/bf47aac7e4f424bc480f0427aeab8b24

**Comment by richo** [comment]
Thanks! It looks like the issue was my outdated rust, I updated my nightly and it works now

**Comment by richo** [comment]
Played around with it a bit locally. Awesome!

**Pull request merged**
